/**
 * Copyright (c) V-Nova International Limited 2014 - 2024
 * All rights reserved.
 *
 * This software is licensed under the BSD-3-Clause-Clear License. No patent licenses
 * are granted under this license. For enquiries about patent licenses, please contact
 * legal@v-nova.com. The LCEVCdecJS software is a stand-alone project and is NOT A
 * CONTRIBUTION to any other project.
 *
 * If the software is incorporated into another project, THE TERMS OF THE
 * BSD-3-CLAUSE-CLEAR LICENSE AND THE ADDITIONAL LICENSING INFORMATION CONTAINED IN
 * THIS FILE MUST BE MAINTAINED, AND THE SOFTWARE DOES NOT AND MUST NOT ADOPT THE
 * LICENSE OF THE INCORPORATING PROJECT. However, the software may be incorporated
 * into a project under a compatible license provided the requirements of the
 * BSD-3-Clause-Clear license are respected, and V-Nova International Limited remains
 * licensor of the software ONLY UNDER the BSD-3-Clause-Clear license (not the
 * compatible license).
 *
 * ANY ONWARD DISTRIBUTION, WHETHER STAND-ALONE OR AS PART OF ANY OTHER PROJECT,
 * REMAINS SUBJECT TO THE EXCLUSION OF PATENT LICENSES PROVISION OF THE
 * BSD-3-CLAUSE-CLEAR LICENSE.
 */

var Module = {}; // eslint-disable-line no-var
if (!Module)
{
	Module = (typeof Module !== 'undefined' ? Module : null) || {};
}


var libDPIModule = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(libDPIModule) {
  libDPIModule = libDPIModule || {};


var e;e||(e=typeof libDPIModule !== 'undefined' ? libDPIModule : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});var h={},l;for(l in e)e.hasOwnProperty(l)&&(h[l]=e[l]);var ca=!1,p=!1;ca="object"===typeof window;p="function"===typeof importScripts;var q="",da;
if(ca||p)p?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),_scriptDir&&(q=_scriptDir),0!==q.indexOf("blob:")?q=q.substr(0,q.lastIndexOf("/")+1):q="",p&&(da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ea=e.print||console.log.bind(console),u=e.printErr||console.warn.bind(console);for(l in h)h.hasOwnProperty(l)&&(e[l]=h[l]);h=null;var v;
e.wasmBinary&&(v=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&w("no native wasm support detected");var fa,ha=!1,ia="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function y(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ia)return ia.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}var ja,z,B,ka,C;
function la(){var a=fa.buffer;ja=a;e.HEAP8=z=new Int8Array(a);e.HEAP16=ka=new Int16Array(a);e.HEAP32=C=new Int32Array(a);e.HEAPU8=B=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAPU32=new Uint32Array(a);e.HEAPF32=new Float32Array(a);e.HEAPF64=new Float64Array(a)}var ma,na=[],oa=[],pa=[];function qa(){var a=e.preRun.shift();na.unshift(a)}var D=0,ra=null,E=null;e.preloadedImages={};e.preloadedAudios={};
function w(a){if(e.onAbort)e.onAbort(a);u(a);ha=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function sa(){return F.startsWith("data:application/octet-stream;base64,")}var F="liblcevc_dpi.wasm";if(!sa()){var ta=F;F=e.locateFile?e.locateFile(ta,q):q+ta}function ua(){var a=F;try{if(a==F&&v)return new Uint8Array(v);if(da)return da(a);throw"both async and sync fetching of the wasm failed";}catch(b){w(b)}}
function va(){return v||!ca&&!p||"function"!==typeof fetch?Promise.resolve().then(function(){return ua()}):fetch(F,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+F+"'";return a.arrayBuffer()}).catch(function(){return ua()})}var H,xa;function ya(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Ma;"number"===typeof c?void 0===b.ja?ma.get(c)():ma.get(c)(b.ja):c(void 0===b.ja?null:b.ja)}}}
function za(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function I(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=za(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Aa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ba(a){if("/"===a)return"/";a=I(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Ca(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){w("randomDevice")}}
function K(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=za(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Da=[];function Ea(a,b){Da[a]={input:[],V:[],ca:b};Fa(a,Ga)}
var Ga={open:function(a){var b=Da[a.node.ha];if(!b)throw new L(43);a.U=b;a.seekable=!1},close:function(a){a.U.ca.flush(a.U)},flush:function(a){a.U.ca.flush(a.U)},read:function(a,b,c,d){if(!a.U||!a.U.ca.sa)throw new L(60);for(var f=0,g=0;g<d;g++){try{var k=a.U.ca.sa(a.U)}catch(m){throw new L(29);}if(void 0===k&&0===f)throw new L(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.U||!a.U.ca.la)throw new L(60);try{for(var f=0;f<d;f++)a.U.ca.la(a.U,
b[c+f])}catch(g){throw new L(29);}d&&(a.node.timestamp=Date.now());return f}},Ha={sa:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;for(var c=0,d=0;d<b.length;++d){var f=b.charCodeAt(d);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|b.charCodeAt(++d)&1023);127>=f?++c:c=2047>=f?c+2:65535>=f?c+3:c+4}c=Array(c+1);var g=
c.length;d=0;if(0<g){f=d;g=d+g-1;for(var k=0;k<b.length;++k){var m=b.charCodeAt(k);if(55296<=m&&57343>=m){var r=b.charCodeAt(++k);m=65536+((m&1023)<<10)|r&1023}if(127>=m){if(d>=g)break;c[d++]=m}else{if(2047>=m){if(d+1>=g)break;c[d++]=192|m>>6}else{if(65535>=m){if(d+2>=g)break;c[d++]=224|m>>12}else{if(d+3>=g)break;c[d++]=240|m>>18;c[d++]=128|m>>12&63}c[d++]=128|m>>6&63}c[d++]=128|m&63}}c[d]=0;b=d-f}else b=0;c.length=b;a.input=c}return a.input.shift()},la:function(a,b){null===b||10===b?(ea(y(a.V,0)),
a.V=[]):0!=b&&a.V.push(b)},flush:function(a){a.V&&0<a.V.length&&(ea(y(a.V,0)),a.V=[])}},Ia={la:function(a,b){null===b||10===b?(u(y(a.V,0)),a.V=[]):0!=b&&a.V.push(b)},flush:function(a){a.V&&0<a.V.length&&(u(y(a.V,0)),a.V=[])}},M={W:null,Y:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.W||(M.W={dir:{node:{$:M.R.$,X:M.R.X,da:M.R.da,fa:M.R.fa,xa:M.R.xa,za:M.R.za,ya:M.R.ya,wa:M.R.wa,ia:M.R.ia},stream:{ba:M.S.ba}},
file:{node:{$:M.R.$,X:M.R.X},stream:{ba:M.S.ba,read:M.S.read,write:M.S.write,na:M.S.na,ta:M.S.ta,va:M.S.va}},link:{node:{$:M.R.$,X:M.R.X,ea:M.R.ea},stream:{}},oa:{node:{$:M.R.$,X:M.R.X},stream:Ja}});c=Ka(a,b,c,d);16384===(c.mode&61440)?(c.R=M.W.dir.node,c.S=M.W.dir.stream,c.P={}):32768===(c.mode&61440)?(c.R=M.W.file.node,c.S=M.W.file.stream,c.T=0,c.P=null):40960===(c.mode&61440)?(c.R=M.W.link.node,c.S=M.W.link.stream):8192===(c.mode&61440)&&(c.R=M.W.oa.node,c.S=M.W.oa.stream);c.timestamp=Date.now();
a&&(a.P[b]=c,a.timestamp=c.timestamp);return c},Na:function(a){return a.P?a.P.subarray?a.P.subarray(0,a.T):new Uint8Array(a.P):new Uint8Array(0)},pa:function(a,b){var c=a.P?a.P.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.P,a.P=new Uint8Array(b),0<a.T&&a.P.set(c.subarray(0,a.T),0))},Ea:function(a,b){if(a.T!=b)if(0==b)a.P=null,a.T=0;else{var c=a.P;a.P=new Uint8Array(b);c&&a.P.set(c.subarray(0,Math.min(b,a.T)));a.T=b}},R:{$:function(a){var b={};b.La=8192===(a.mode&
61440)?a.id:1;b.Pa=a.id;b.mode=a.mode;b.Ra=1;b.uid=0;b.Oa=0;b.ha=a.ha;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.T:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Ia=new Date(a.timestamp);b.Qa=new Date(a.timestamp);b.Ka=new Date(a.timestamp);b.Aa=4096;b.Ja=Math.ceil(b.size/b.Aa);return b},X:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.Ea(a,b.size)},da:function(){throw La[44];},fa:function(a,b,c,d){return M.createNode(a,
b,c,d)},xa:function(a,b,c){if(16384===(a.mode&61440)){try{var d=N(b,c)}catch(g){}if(d)for(var f in d.P)throw new L(55);}delete a.parent.P[a.name];a.parent.timestamp=Date.now();a.name=c;b.P[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},za:function(a,b){delete a.P[b];a.timestamp=Date.now()},ya:function(a,b){var c=N(a,b),d;for(d in c.P)throw new L(55);delete a.P[b];a.timestamp=Date.now()},wa:function(a){var b=[".",".."],c;for(c in a.P)a.P.hasOwnProperty(c)&&b.push(c);return b},ia:function(a,b,c){a=
M.createNode(a,b,41471,0);a.link=c;return a},ea:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},S:{read:function(a,b,c,d,f){var g=a.node.P;if(f>=a.node.T)return 0;a=Math.min(a.node.T-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){b.buffer===z.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.P||a.P.subarray)){if(g)return a.P=b.subarray(c,c+d),a.T=d;if(0===a.T&&0===f)return a.P=
b.slice(c,c+d),a.T=d;if(f+d<=a.T)return a.P.set(b.subarray(c,c+d),f),d}M.pa(a,f+d);if(a.P.subarray&&b.subarray)a.P.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.P[f+g]=b[c+g];a.T=Math.max(a.T,f+d);return d},ba:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.T);if(0>b)throw new L(28);return b},na:function(a,b,c){M.pa(a.node,b+c);a.node.T=Math.max(a.node.T,b+c)},ta:function(a,b,c,d,f,g){if(0!==b)throw new L(28);if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.P;
if(g&2||a.buffer!==ja){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=65536*Math.ceil(c/65536);for(b=Ma(g);c<g;)z[b+c++]=0;c=b;if(!c)throw new L(48);z.set(a,c)}else d=!1,c=a.byteOffset;return{Ta:c,Ha:d}},va:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new L(43);if(f&2)return 0;M.S.write(a,b,0,d,c,!1);return 0}}},Na=null,Oa={},O=[],Pa=1,P=null,Q={},L=null,La={};
function R(a,b){a=K("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ra:!0,ma:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ma)throw new L(32);a=za(a.split("/").filter(function(k){return!!k}),!1);var f=Na;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=N(f,a[d]);c=I(c+"/"+a[d]);f.ga&&(!g||g&&b.ra)&&(f=f.ga.root);if(!g||b.qa)for(g=0;40960===(f.mode&61440);)if(f=Qa(c),c=K(Aa(c),f),f=R(c,{ma:b.ma}).node,40<g++)throw new L(32);}return{path:c,node:f}}
function Ra(a){for(var b;;){if(a===a.parent)return a=a.Y.ua,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Sa(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%P.length}function N(a,b){var c;if(c=a.R.da?0:2)throw new L(c,a);for(c=P[Sa(a.id,b)];c;c=c.Da){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.R.da(a,b)}function Ka(a,b,c,d){a=new Ta(a,b,c,d);b=Sa(a.parent.id,a.name);a.Da=P[b];return P[b]=a}
var Ua={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Va(a,b){try{return N(a,b),20}catch(c){}return 0}function Wa(a){var b=4096;for(a=a||0;a<=b;a++)if(!O[a])return a;throw new L(33);}function Xa(a,b){Ya||(Ya=function(){},Ya.prototype={});var c=new Ya,d;for(d in a)c[d]=a[d];a=c;b=Wa(b);a.Z=b;return O[b]=a}var Ja={open:function(a){a.S=Oa[a.node.ha].S;a.S.open&&a.S.open(a)},ba:function(){throw new L(70);}};function Fa(a,b){Oa[a]={S:b}}
function Za(a,b){var c="/"===b,d=!b;if(c&&Na)throw new L(10);if(!c&&!d){var f=R(b,{ra:!1});b=f.path;f=f.node;if(f.ga)throw new L(10);if(16384!==(f.mode&61440))throw new L(54);}b={type:a,Sa:{},ua:b,Ca:[]};a=a.Y(b);a.Y=b;b.root=a;c?Na=a:f&&(f.ga=b,f.Y&&f.Y.Ca.push(b))}function $a(a,b,c){var d=R(a,{parent:!0}).node;a=Ba(a);if(!a||"."===a||".."===a)throw new L(28);var f=Va(d,a);if(f)throw new L(f);if(!d.R.fa)throw new L(63);return d.R.fa(d,a,b,c)}function S(a){return $a(a,16895,0)}
function ab(a,b,c){"undefined"===typeof c&&(c=b,b=438);$a(a,b|8192,c)}function bb(a,b){if(!K(a))throw new L(44);var c=R(b,{parent:!0}).node;if(!c)throw new L(44);b=Ba(b);var d=Va(c,b);if(d)throw new L(d);if(!c.R.ia)throw new L(63);c.R.ia(c,b,a)}function Qa(a){a=R(a).node;if(!a)throw new L(44);if(!a.R.ea)throw new L(28);return K(Ra(a.parent),a.R.ea(a))}
function T(a,b,c,d){if(""===a)throw new L(44);if("string"===typeof b){var f=Ua[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=I(a);try{g=R(a,{qa:!(b&131072)}).node}catch(k){}}f=!1;if(b&64)if(g){if(b&128)throw new L(20);}else g=$a(a,c,0),f=!0;if(!g)throw new L(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new L(54);if(!f){if(g)if(40960===(g.mode&61440))c=
32;else{if(c=16384===(g.mode&61440))c=["r","w","rw"][b&3],b&512&&(c+="w"),c="r"!==c||b&512;c=c?31:0}else c=44;if(c)throw new L(c);}if(b&512){c=g;c="string"===typeof c?R(c,{qa:!0}).node:c;if(!c.R.X)throw new L(63);if(16384===(c.mode&61440))throw new L(31);if(32768!==(c.mode&61440))throw new L(28);c.R.X(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Xa({node:g,path:Ra(g),flags:b,seekable:!0,position:0,S:g.S,Ga:[],error:!1},d);d.S.open&&d.S.open(d);!e.logReadFiles||b&1||(cb||(cb={}),a in cb||(cb[a]=1,
u("FS.trackingDelegate error on read file: "+a)));try{Q.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Q.onOpenFile(a,g))}catch(k){u("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function db(a,b,c){if(null===a.Z)throw new L(8);if(!a.seekable||!a.S.ba)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.S.ba(a,b,c);a.Ga=[]}
function eb(){L||(L=function(a,b){this.node=b;this.Fa=function(c){this.aa=c};this.Fa(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(function(a){La[a]=new L(a);La[a].stack="<generic error, no stack>"}))}var fb;function gb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function V(a,b,c){a=I("/dev/"+a);var d=gb(!!b,!!c);hb||(hb=64);var f=hb++<<8|0;Fa(f,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,k,m,r){for(var n=0,t=0;t<r;t++){try{var x=b()}catch(G){throw new L(29);}if(void 0===x&&0===n)throw new L(6);if(null===x||void 0===x)break;n++;k[m+t]=x}n&&(g.node.timestamp=Date.now());return n},write:function(g,k,m,r){for(var n=0;n<r;n++)try{c(k[m+n])}catch(t){throw new L(29);}r&&(g.node.timestamp=Date.now());return n}});
ab(a,d,f)}var hb,W={},Ya,cb,X=void 0;function Y(){X+=4;return C[X-4>>2]}function Z(a){a=O[a];if(!a)throw new L(8);return a}var ib;ib=function(){return performance.now()};function Ta(a,b,c,d){a||(a=this);this.parent=a;this.Y=a.Y;this.ga=null;this.id=Pa++;this.name=b;this.mode=c;this.R={};this.S={};this.ha=d}
Object.defineProperties(Ta.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});eb();P=Array(4096);Za(M,"/");S("/tmp");S("/home");S("/home/web_user");
(function(){S("/dev");Fa(259,{read:function(){return 0},write:function(b,c,d,f){return f}});ab("/dev/null",259);Ea(1280,Ha);Ea(1536,Ia);ab("/dev/tty",1280);ab("/dev/tty1",1536);var a=Ca();V("random",a);V("urandom",a);S("/dev/shm");S("/dev/shm/tmp")})();
(function(){S("/proc");var a=S("/proc/self");S("/proc/self/fd");Za({Y:function(){var b=Ka(a,"fd",16895,73);b.R={da:function(c,d){var f=O[+d];if(!f)throw new L(8);c={parent:null,Y:{ua:"fake"},R:{ea:function(){return f.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();
var kb={c:function(a,b,c){X=c;try{var d=Z(a);switch(b){case 0:var f=Y();return 0>f?-28:T(d.path,d.flags,0,f).Z;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Y(),d.flags|=f,0;case 12:return f=Y(),ka[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return C[jb()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof W&&g instanceof L||w(g),-g.aa}},g:function(a,b,c){X=c;try{var d=Z(a);switch(b){case 21509:case 21505:return d.U?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.U?
0:-59;case 21519:if(!d.U)return-59;var f=Y();return C[f>>2]=0;case 21520:return d.U?-28:-59;case 21531:a=f=Y();if(!d.S.Ba)throw new L(59);return d.S.Ba(d,b,a);case 21523:return d.U?0:-59;case 21524:return d.U?0:-59;default:w("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof W&&g instanceof L||w(g),-g.aa}},h:function(a,b,c){X=c;try{var d=a?y(B,a,void 0):"",f=c?Y():0;return T(d,b,f).Z}catch(g){return"undefined"!==typeof W&&g instanceof L||w(g),-g.aa}},k:function(a,b){if(0===a)a=Date.now();
else if(1===a||4===a)a=ib();else return C[jb()>>2]=28,-1;C[b>>2]=a/1E3|0;C[b+4>>2]=a%1E3*1E6|0;return 0},l:function(a,b,c){B.copyWithin(a,b,b+c)},m:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{fa.grow(Math.min(2147483648,d)-ja.byteLength+65535>>>16);la();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},a:function(a){try{var b=Z(a);if(null===b.Z)throw new L(8);
b.ka&&(b.ka=null);try{b.S.close&&b.S.close(b)}catch(c){throw c;}finally{O[b.Z]=null}b.Z=null;return 0}catch(c){return"undefined"!==typeof W&&c instanceof L||w(c),c.aa}},f:function(a,b,c,d){try{a:{for(var f=Z(a),g=a=0;g<c;g++){var k=C[b+(8*g+4)>>2],m=f,r=C[b+8*g>>2],n=k,t=void 0,x=z;if(0>n||0>t)throw new L(28);if(null===m.Z)throw new L(8);if(1===(m.flags&2097155))throw new L(8);if(16384===(m.node.mode&61440))throw new L(31);if(!m.S.read)throw new L(28);var G="undefined"!==typeof t;if(!G)t=m.position;
else if(!m.seekable)throw new L(70);var U=m.S.read(m,x,r,n,t);G||(m.position+=U);var J=U;if(0>J){var A=-1;break a}a+=J;if(J<k)break}A=a}C[d>>2]=A;return 0}catch(wa){return"undefined"!==typeof W&&wa instanceof L||w(wa),wa.aa}},i:function(a,b,c,d,f){try{var g=Z(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;db(g,a,d);xa=[g.position>>>0,(H=g.position,1<=+Math.abs(H)?0<H?(Math.min(+Math.floor(H/4294967296),4294967295)|0)>>>0:~~+Math.ceil((H-+(~~H>>>0))/4294967296)>>>
0:0)];C[f>>2]=xa[0];C[f+4>>2]=xa[1];g.ka&&0===a&&0===d&&(g.ka=null);return 0}catch(k){return"undefined"!==typeof W&&k instanceof L||w(k),k.aa}},b:function(a,b,c,d){try{a:{for(var f=Z(a),g=a=0;g<c;g++){var k=f,m=C[b+8*g>>2],r=C[b+(8*g+4)>>2],n=void 0,t=z;if(0>r||0>n)throw new L(28);if(null===k.Z)throw new L(8);if(0===(k.flags&2097155))throw new L(8);if(16384===(k.node.mode&61440))throw new L(31);if(!k.S.write)throw new L(28);k.seekable&&k.flags&1024&&db(k,0,2);var x="undefined"!==typeof n;if(!x)n=
k.position;else if(!k.seekable)throw new L(70);var G=k.S.write(k,t,m,r,n,void 0);x||(k.position+=G);try{if(k.path&&Q.onWriteToFile)Q.onWriteToFile(k.path)}catch(A){u("FS.trackingDelegate['onWriteToFile']('"+k.path+"') threw an exception: "+A.message)}var U=G;if(0>U){var J=-1;break a}a+=U}J=a}C[d>>2]=J;return 0}catch(A){return"undefined"!==typeof W&&A instanceof L||w(A),A.aa}},e:function(){return 6},d:function(){return 28},j:function(a){var b=Date.now()/1E3|0;a&&(C[a>>2]=b);return b}};
(function(){function a(f){e.asm=f.exports;fa=e.asm.n;la();ma=e.asm.O;oa.unshift(e.asm.o);D--;e.monitorRunDependencies&&e.monitorRunDependencies(D);0==D&&(null!==ra&&(clearInterval(ra),ra=null),E&&(f=E,E=null,f()))}function b(f){a(f.instance)}function c(f){return va().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){u("failed to asynchronously prepare wasm: "+g);w(g)})}var d={a:kb};D++;e.monitorRunDependencies&&e.monitorRunDependencies(D);if(e.instantiateWasm)try{return e.instantiateWasm(d,
a)}catch(f){return u("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return v||"function"!==typeof WebAssembly.instantiateStreaming||sa()||"function"!==typeof fetch?c(b):fetch(F,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){u("wasm streaming compile failed: "+g);u("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.o).apply(null,arguments)};e._DPIVersion=function(){return(e._DPIVersion=e.asm.p).apply(null,arguments)};e._DPIVersionFull=function(){return(e._DPIVersionFull=e.asm.q).apply(null,arguments)};e._DPIHash=function(){return(e._DPIHash=e.asm.r).apply(null,arguments)};e._DPIHashShort=function(){return(e._DPIHashShort=e.asm.s).apply(null,arguments)};e._perseus_get_version=function(){return(e._perseus_get_version=e.asm.t).apply(null,arguments)};
e._perseus_decoder_close=function(){return(e._perseus_decoder_close=e.asm.u).apply(null,arguments)};e._perseus_decoder_parse=function(){return(e._perseus_decoder_parse=e.asm.v).apply(null,arguments)};e._perseus_decoder_get_dither_strength=function(){return(e._perseus_decoder_get_dither_strength=e.asm.w).apply(null,arguments)};e._perseus_decoder_get_dither_type=function(){return(e._perseus_decoder_get_dither_type=e.asm.x).apply(null,arguments)};
e._perseus_decoder_clear_temporal=function(){return(e._perseus_decoder_clear_temporal=e.asm.y).apply(null,arguments)};e._perseus_decoder_open_wrapper=function(){return(e._perseus_decoder_open_wrapper=e.asm.z).apply(null,arguments)};e._perseus_decoder_decode_wrapper=function(){return(e._perseus_decoder_decode_wrapper=e.asm.A).apply(null,arguments)};e._perseus_decoder_decode_base_wrapper=function(){return(e._perseus_decoder_decode_base_wrapper=e.asm.B).apply(null,arguments)};
e._perseus_decoder_decode_high_wrapper=function(){return(e._perseus_decoder_decode_high_wrapper=e.asm.C).apply(null,arguments)};e._perseus_decoder_upscale_wrapper=function(){return(e._perseus_decoder_upscale_wrapper=e.asm.D).apply(null,arguments)};e._perseus_decoder_parse_wrapper=function(){return(e._perseus_decoder_parse_wrapper=e.asm.E).apply(null,arguments)};e._perseus_decoder_get_surface_size=function(){return(e._perseus_decoder_get_surface_size=e.asm.F).apply(null,arguments)};
e._perseus_decoder_get_base_hash=function(){return(e._perseus_decoder_get_base_hash=e.asm.G).apply(null,arguments)};e._perseus_start_tracing=function(){return(e._perseus_start_tracing=e.asm.H).apply(null,arguments)};e._perseus_end_tracing=function(){return(e._perseus_end_tracing=e.asm.I).apply(null,arguments)};e._perseus_decoder_get_last_error_wrapper=function(){return(e._perseus_decoder_get_last_error_wrapper=e.asm.J).apply(null,arguments)};
e._perseus_decoder_get_surface=function(){return(e._perseus_decoder_get_surface=e.asm.K).apply(null,arguments)};var jb=e.___errno_location=function(){return(jb=e.___errno_location=e.asm.L).apply(null,arguments)},Ma=e._malloc=function(){return(Ma=e._malloc=e.asm.M).apply(null,arguments)};e._free=function(){return(e._free=e.asm.N).apply(null,arguments)};var lb;E=function mb(){lb||nb();lb||(E=mb)};
function nb(){function a(){if(!lb&&(lb=!0,e.calledRun=!0,!ha)){e.noFSInit||fb||(fb=!0,eb(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?V("stdin",e.stdin):bb("/dev/tty","/dev/stdin"),e.stdout?V("stdout",null,e.stdout):bb("/dev/tty","/dev/stdout"),e.stderr?V("stderr",null,e.stderr):bb("/dev/tty1","/dev/stderr"),T("/dev/stdin",0),T("/dev/stdout",1),T("/dev/stderr",1));ya(oa);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=
[e.postRun]);e.postRun.length;){var b=e.postRun.shift();pa.unshift(b)}ya(pa)}}if(!(0<D)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)qa();ya(na);0<D||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=nb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();nb();


  return libDPIModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = libDPIModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return libDPIModule; });
else if (typeof exports === 'object')
  exports["libDPIModule"] = libDPIModule;
