/**
 * Copyright (c) V-Nova International Limited 2014 - 2024
 * All rights reserved.
 *
 * This software is licensed under the BSD-3-Clause-Clear License. No patent licenses
 * are granted under this license. For enquiries about patent licenses, please contact
 * legal@v-nova.com. The LCEVCdecJS software is a stand-alone project and is NOT A
 * CONTRIBUTION to any other project.
 *
 * If the software is incorporated into another project, THE TERMS OF THE
 * BSD-3-CLAUSE-CLEAR LICENSE AND THE ADDITIONAL LICENSING INFORMATION CONTAINED IN
 * THIS FILE MUST BE MAINTAINED, AND THE SOFTWARE DOES NOT AND MUST NOT ADOPT THE
 * LICENSE OF THE INCORPORATING PROJECT. However, the software may be incorporated
 * into a project under a compatible license provided the requirements of the
 * BSD-3-Clause-Clear license are respected, and V-Nova International Limited remains
 * licensor of the software ONLY UNDER the BSD-3-Clause-Clear license (not the
 * compatible license).
 *
 * ANY ONWARD DISTRIBUTION, WHETHER STAND-ALONE OR AS PART OF ANY OTHER PROJECT,
 * REMAINS SUBJECT TO THE EXCLUSION OF PATENT LICENSES PROVISION OF THE
 * BSD-3-CLAUSE-CLEAR LICENSE.
 */

var Module = {}; // eslint-disable-line no-var
if (!Module)
{
	Module = (typeof Module !== 'undefined' ? Module : null) || {};
}


var libDPIModule = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(libDPIModule) {
  libDPIModule = libDPIModule || {};


var e;e||(e=typeof libDPIModule !== 'undefined' ? libDPIModule : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});var k={},p;for(p in e)e.hasOwnProperty(p)&&(k[p]=e[p]);var x="";"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src);_scriptDir&&(x=_scriptDir);0!==x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="";var ca=e.print||console.log.bind(console),y=e.printErr||console.warn.bind(console);for(p in k)k.hasOwnProperty(p)&&(e[p]=k[p]);k=null;
function da(a){A||(A={});A[a]||(A[a]=1,y(a))}var A,B;e.wasmBinary&&(B=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&E("no native wasm support detected");var ea,fa=!1,ha="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function F(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ha)return ha.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}var ia,G,H,ja,I,ka;
function la(){var a=ea.buffer;ia=a;e.HEAP8=G=new Int8Array(a);e.HEAP16=ja=new Int16Array(a);e.HEAP32=I=new Int32Array(a);e.HEAPU8=H=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAPU32=new Uint32Array(a);e.HEAPF32=new Float32Array(a);e.HEAPF64=ka=new Float64Array(a)}var ma,na=[],oa=[],pa=[];function qa(){var a=e.preRun.shift();na.unshift(a)}var J=0,ra=null,K=null;e.preloadedImages={};e.preloadedAudios={};
function E(a){if(e.onAbort)e.onAbort(a);y(a);fa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function sa(){return L.startsWith("data:application/octet-stream;base64,")}var L="liblcevc_dpi.wasm";if(!sa()){var ta=L;L=e.locateFile?e.locateFile(ta,x):x+ta}function ua(){var a=L;try{if(a==L&&B)return new Uint8Array(B);throw"both async and sync fetching of the wasm failed";}catch(b){E(b)}}
function va(){return B||"function"!==typeof fetch?Promise.resolve().then(function(){return ua()}):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return ua()})}var M,wa;function ya(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Ma;"number"===typeof c?void 0===b.ia?ma.get(c)():ma.get(c)(b.ia):c(void 0===b.ia?null:b.ia)}}}
function za(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function N(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=za(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Aa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ba(a){if("/"===a)return"/";a=N(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Ca(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){E("randomDevice")}}
function Da(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=za(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Ea=[];function Fa(a,b){Ea[a]={input:[],U:[],ba:b};Ga(a,Ha)}
var Ha={open:function(a){var b=Ea[a.node.ga];if(!b)throw new O(43);a.T=b;a.seekable=!1},close:function(a){a.T.ba.flush(a.T)},flush:function(a){a.T.ba.flush(a.T)},read:function(a,b,c,d){if(!a.T||!a.T.ba.ra)throw new O(60);for(var f=0,g=0;g<d;g++){try{var h=a.T.ba.ra(a.T)}catch(m){throw new O(29);}if(void 0===h&&0===f)throw new O(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.T||!a.T.ba.ka)throw new O(60);try{for(var f=0;f<d;f++)a.T.ba.ka(a.T,
b[c+f])}catch(g){throw new O(29);}d&&(a.node.timestamp=Date.now());return f}},Ja={ra:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Ia(b)}return a.input.shift()},ka:function(a,b){null===b||10===b?(ca(F(a.U,0)),a.U=[]):0!=b&&a.U.push(b)},flush:function(a){a.U&&0<a.U.length&&(ca(F(a.U,0)),a.U=[])}},Ka={ka:function(a,
b){null===b||10===b?(y(F(a.U,0)),a.U=[]):0!=b&&a.U.push(b)},flush:function(a){a.U&&0<a.U.length&&(y(F(a.U,0)),a.U=[])}},P={V:null,X:function(){return P.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new O(63);P.V||(P.V={dir:{node:{Z:P.P.Z,W:P.P.W,ca:P.P.ca,ea:P.P.ea,wa:P.P.wa,ya:P.P.ya,xa:P.P.xa,va:P.P.va,ha:P.P.ha},stream:{aa:P.R.aa}},file:{node:{Z:P.P.Z,W:P.P.W},stream:{aa:P.R.aa,read:P.R.read,write:P.R.write,ma:P.R.ma,sa:P.R.sa,ua:P.R.ua}},
link:{node:{Z:P.P.Z,W:P.P.W,da:P.P.da},stream:{}},na:{node:{Z:P.P.Z,W:P.P.W},stream:La}});c=Ma(a,b,c,d);16384===(c.mode&61440)?(c.P=P.V.dir.node,c.R=P.V.dir.stream,c.O={}):32768===(c.mode&61440)?(c.P=P.V.file.node,c.R=P.V.file.stream,c.S=0,c.O=null):40960===(c.mode&61440)?(c.P=P.V.link.node,c.R=P.V.link.stream):8192===(c.mode&61440)&&(c.P=P.V.na.node,c.R=P.V.na.stream);c.timestamp=Date.now();a&&(a.O[b]=c,a.timestamp=c.timestamp);return c},Na:function(a){return a.O?a.O.subarray?a.O.subarray(0,a.S):
new Uint8Array(a.O):new Uint8Array(0)},oa:function(a,b){var c=a.O?a.O.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.O,a.O=new Uint8Array(b),0<a.S&&a.O.set(c.subarray(0,a.S),0))},Ea:function(a,b){if(a.S!=b)if(0==b)a.O=null,a.S=0;else{var c=a.O;a.O=new Uint8Array(b);c&&a.O.set(c.subarray(0,Math.min(b,a.S)));a.S=b}},P:{Z:function(a){var b={};b.La=8192===(a.mode&61440)?a.id:1;b.Pa=a.id;b.mode=a.mode;b.Ra=1;b.uid=0;b.Oa=0;b.ga=a.ga;16384===(a.mode&61440)?b.size=
4096:32768===(a.mode&61440)?b.size=a.S:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Ia=new Date(a.timestamp);b.Qa=new Date(a.timestamp);b.Ka=new Date(a.timestamp);b.za=4096;b.Ja=Math.ceil(b.size/b.za);return b},W:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&P.Ea(a,b.size)},ca:function(){throw Na[44];},ea:function(a,b,c,d){return P.createNode(a,b,c,d)},wa:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Oa(b,c)}catch(g){}if(d)for(var f in d.O)throw new O(55);
}delete a.parent.O[a.name];a.parent.timestamp=Date.now();a.name=c;b.O[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},ya:function(a,b){delete a.O[b];a.timestamp=Date.now()},xa:function(a,b){var c=Oa(a,b),d;for(d in c.O)throw new O(55);delete a.O[b];a.timestamp=Date.now()},va:function(a){var b=[".",".."],c;for(c in a.O)a.O.hasOwnProperty(c)&&b.push(c);return b},ha:function(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},da:function(a){if(40960!==(a.mode&61440))throw new O(28);return a.link}},
R:{read:function(a,b,c,d,f){var g=a.node.O;if(f>=a.node.S)return 0;a=Math.min(a.node.S-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){b.buffer===G.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.O||a.O.subarray)){if(g)return a.O=b.subarray(c,c+d),a.S=d;if(0===a.S&&0===f)return a.O=b.slice(c,c+d),a.S=d;if(f+d<=a.S)return a.O.set(b.subarray(c,c+d),f),d}P.oa(a,f+d);if(a.O.subarray&&b.subarray)a.O.set(b.subarray(c,
c+d),f);else for(g=0;g<d;g++)a.O[f+g]=b[c+g];a.S=Math.max(a.S,f+d);return d},aa:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.S);if(0>b)throw new O(28);return b},ma:function(a,b,c){P.oa(a.node,b+c);a.node.S=Math.max(a.node.S,b+c)},sa:function(a,b,c,d,f,g){if(0!==b)throw new O(28);if(32768!==(a.node.mode&61440))throw new O(43);a=a.node.O;if(g&2||a.buffer!==ia){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=65536*
Math.ceil(c/65536);for(b=Pa(g);c<g;)G[b+c++]=0;c=b;if(!c)throw new O(48);G.set(a,c)}else d=!1,c=a.byteOffset;return{Ua:c,Ha:d}},ua:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new O(43);if(f&2)return 0;P.R.write(a,b,0,d,c,!1);return 0}}},Qa=null,Ra={},Q=[],Sa=1,R=null,Ta={},O=null,Na={};
function S(a,b){a=Da("/",a);b=b||{};if(!a)return{path:"",node:null};var c={qa:!0,la:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.la)throw new O(32);a=za(a.split("/").filter(function(h){return!!h}),!1);var f=Qa;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Oa(f,a[d]);c=N(c+"/"+a[d]);f.fa&&(!g||g&&b.qa)&&(f=f.fa.root);if(!g||b.pa)for(g=0;40960===(f.mode&61440);)if(f=Ua(c),c=Da(Aa(c),f),f=S(c,{la:b.la}).node,40<g++)throw new O(32);}return{path:c,node:f}}
function Va(a){for(var b;;){if(a===a.parent)return a=a.X.ta,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Wa(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function Oa(a,b){var c;if(c=a.P.ca?0:2)throw new O(c,a);for(c=R[Wa(a.id,b)];c;c=c.Da){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.P.ca(a,b)}function Ma(a,b,c,d){a=new Xa(a,b,c,d);b=Wa(a.parent.id,a.name);a.Da=R[b];return R[b]=a}
var Ya={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Za(a,b){try{return Oa(a,b),20}catch(c){}return 0}function $a(a){var b=4096;for(a=a||0;a<=b;a++)if(!Q[a])return a;throw new O(33);}function ab(a,b){bb||(bb=function(){},bb.prototype={});var c=new bb,d;for(d in a)c[d]=a[d];a=c;b=$a(b);a.Y=b;return Q[b]=a}var La={open:function(a){a.R=Ra[a.node.ga].R;a.R.open&&a.R.open(a)},aa:function(){throw new O(70);}};function Ga(a,b){Ra[a]={R:b}}
function cb(a,b){var c="/"===b,d=!b;if(c&&Qa)throw new O(10);if(!c&&!d){var f=S(b,{qa:!1});b=f.path;f=f.node;if(f.fa)throw new O(10);if(16384!==(f.mode&61440))throw new O(54);}b={type:a,Sa:{},ta:b,Ca:[]};a=a.X(b);a.X=b;b.root=a;c?Qa=a:f&&(f.fa=b,f.X&&f.X.Ca.push(b))}function db(a,b,c){var d=S(a,{parent:!0}).node;a=Ba(a);if(!a||"."===a||".."===a)throw new O(28);var f=Za(d,a);if(f)throw new O(f);if(!d.P.ea)throw new O(63);return d.P.ea(d,a,b,c)}function T(a){return db(a,16895,0)}
function eb(a,b,c){"undefined"===typeof c&&(c=b,b=438);db(a,b|8192,c)}function fb(a,b){if(!Da(a))throw new O(44);var c=S(b,{parent:!0}).node;if(!c)throw new O(44);b=Ba(b);var d=Za(c,b);if(d)throw new O(d);if(!c.P.ha)throw new O(63);c.P.ha(c,b,a)}function Ua(a){a=S(a).node;if(!a)throw new O(44);if(!a.P.da)throw new O(28);return Da(Va(a.parent),a.P.da(a))}
function U(a,b,c,d){if(""===a)throw new O(44);if("string"===typeof b){var f=Ya[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=N(a);try{g=S(a,{pa:!(b&131072)}).node}catch(h){}}f=!1;if(b&64)if(g){if(b&128)throw new O(20);}else g=db(a,c,0),f=!0;if(!g)throw new O(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new O(54);if(!f){if(g)if(40960===(g.mode&61440))c=
32;else{if(c=16384===(g.mode&61440))c=["r","w","rw"][b&3],b&512&&(c+="w"),c="r"!==c||b&512;c=c?31:0}else c=44;if(c)throw new O(c);}if(b&512){c=g;c="string"===typeof c?S(c,{pa:!0}).node:c;if(!c.P.W)throw new O(63);if(16384===(c.mode&61440))throw new O(31);if(32768!==(c.mode&61440))throw new O(28);c.P.W(c,{size:0,timestamp:Date.now()})}b&=-131713;d=ab({node:g,path:Va(g),flags:b,seekable:!0,position:0,R:g.R,Ga:[],error:!1},d);d.R.open&&d.R.open(d);!e.logReadFiles||b&1||(gb||(gb={}),a in gb||(gb[a]=1,
y("FS.trackingDelegate error on read file: "+a)));try{Ta.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Ta.onOpenFile(a,g))}catch(h){y("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return d}function hb(a,b,c){if(null===a.Y)throw new O(8);if(!a.seekable||!a.R.aa)throw new O(70);if(0!=c&&1!=c&&2!=c)throw new O(28);a.position=a.R.aa(a,b,c);a.Ga=[]}
function ib(){O||(O=function(a,b){this.node=b;this.Fa=function(c){this.$=c};this.Fa(a);this.message="FS error"},O.prototype=Error(),O.prototype.constructor=O,[44].forEach(function(a){Na[a]=new O(a);Na[a].stack="<generic error, no stack>"}))}var jb;function kb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function V(a,b,c){a=N("/dev/"+a);var d=kb(!!b,!!c);lb||(lb=64);var f=lb++<<8|0;Ga(f,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,h,m,t){for(var n=0,r=0;r<t;r++){try{var z=b()}catch(w){throw new O(29);}if(void 0===z&&0===n)throw new O(6);if(null===z||void 0===z)break;n++;h[m+r]=z}n&&(g.node.timestamp=Date.now());return n},write:function(g,h,m,t){for(var n=0;n<t;n++)try{c(h[m+n])}catch(r){throw new O(29);}t&&(g.node.timestamp=Date.now());return n}});
eb(a,d,f)}var lb,W={},bb,gb,X=void 0;function Y(){X+=4;return I[X-4>>2]}function Z(a){a=Q[a];if(!a)throw new O(8);return a}function mb(a,b){if(0>=a)return a;var c=32>=b?Math.abs(1<<b-1):Math.pow(2,b-1);a>=c&&(32>=b||a>c)&&(a=-2*c+a);return a}function nb(a,b){return 0<=a?a:32>=b?2*Math.abs(1<<b-1)+a:Math.pow(2,b)+a}
function ob(a,b){function c(C){var xa=d;("double"===C||"i64"===C)&&xa&7&&(xa+=4);d=xa;"double"===C?(C=ka[d>>3],d+=8):"i64"==C?(C=[I[d>>2],I[d+4>>2]],d+=8):(C=I[d>>2],d+=4);return C}for(var d=b,f=[],g,h;;){var m=a;g=G[a>>0];if(0===g)break;h=G[a+1>>0];if(37==g){var t=!1,n=b=!1,r=!1,z=!1;a:for(;;){switch(h){case 43:t=!0;break;case 45:b=!0;break;case 35:n=!0;break;case 48:if(r)break a;else{r=!0;break}case 32:z=!0;break;default:break a}a++;h=G[a+1>>0]}var w=0;if(42==h)w=c("i32"),a++,h=G[a+1>>0];else for(;48<=
h&&57>=h;)w=10*w+(h-48),a++,h=G[a+1>>0];var v=!1,u=-1;if(46==h){u=0;v=!0;a++;h=G[a+1>>0];if(42==h)u=c("i32"),a++;else for(;;){h=G[a+1>>0];if(48>h||57<h)break;u=10*u+(h-48);a++}h=G[a+1>>0]}0>u&&(u=6,v=!1);switch(String.fromCharCode(h)){case "h":h=G[a+2>>0];if(104==h){a++;var q=1}else q=2;break;case "l":h=G[a+2>>0];108==h?(a++,q=8):q=4;break;case "L":case "q":case "j":q=8;break;case "z":case "t":case "I":q=4;break;default:q=null}q&&a++;h=G[a+1>>0];switch(String.fromCharCode(h)){case "d":case "i":case "u":case "o":case "x":case "X":case "p":m=
100==h||105==h;q=q||4;g=c("i"+8*q);8==q&&(g=117==h?(g[0]>>>0)+4294967296*(g[1]>>>0):(g[0]>>>0)+4294967296*g[1]);4>=q&&(g=(m?mb:nb)(g&Math.pow(256,q)-1,8*q));var D=Math.abs(g);m="";if(100==h||105==h)var l=mb(g,8*q,1).toString(10);else if(117==h)l=nb(g,8*q,1).toString(10),g=Math.abs(g);else if(111==h)l=(n?"0":"")+D.toString(8);else if(120==h||88==h){m=n&&0!=g?"0x":"";if(0>g){g=-g;l=(D-1).toString(16);D=[];for(n=0;n<l.length;n++)D.push((15-parseInt(l[n],16)).toString(16));for(l=D.join("");l.length<2*
q;)l="f"+l}else l=D.toString(16);88==h&&(m=m.toUpperCase(),l=l.toUpperCase())}else 112==h&&(0===D?l="(nil)":(m="0x",l=D.toString(16)));if(v)for(;l.length<u;)l="0"+l;0<=g&&(t?m="+"+m:z&&(m=" "+m));"-"==l.charAt(0)&&(m="-"+m,l=l.substr(1));for(;m.length+l.length<w;)b?l+=" ":r?l="0"+l:m=" "+m;l=m+l;l.split("").forEach(function(C){f.push(C.charCodeAt(0))});break;case "f":case "F":case "e":case "E":case "g":case "G":g=c("double");if(isNaN(g))l="nan",r=!1;else if(isFinite(g)){v=!1;q=Math.min(u,20);if(103==
h||71==h)v=!0,u=u||1,q=parseInt(g.toExponential(q).split("e")[1],10),u>q&&-4<=q?(h=(103==h?"f":"F").charCodeAt(0),u-=q+1):(h=(103==h?"e":"E").charCodeAt(0),u--),q=Math.min(u,20);if(101==h||69==h)l=g.toExponential(q),/[eE][-+]\d$/.test(l)&&(l=l.slice(0,-1)+"0"+l.slice(-1));else if(102==h||70==h)l=g.toFixed(q),0===g&&(0>g||0===g&&-Infinity===1/g)&&(l="-"+l);m=l.split("e");if(v&&!n)for(;1<m[0].length&&m[0].includes(".")&&("0"==m[0].slice(-1)||"."==m[0].slice(-1));)m[0]=m[0].slice(0,-1);else for(n&&-1==
l.indexOf(".")&&(m[0]+=".");u>q++;)m[0]+="0";l=m[0]+(1<m.length?"e"+m[1]:"");69==h&&(l=l.toUpperCase());0<=g&&(t?l="+"+l:z&&(l=" "+l))}else l=(0>g?"-":"")+"inf",r=!1;for(;l.length<w;)l=b?l+" ":!r||"-"!=l[0]&&"+"!=l[0]?(r?"0":" ")+l:l[0]+"0"+l.slice(1);97>h&&(l=l.toUpperCase());l.split("").forEach(function(C){f.push(C.charCodeAt(0))});break;case "s":r=(t=c("i8*"))?pb(t):6;v&&(r=Math.min(r,u));if(!b)for(;r<w--;)f.push(32);if(t)for(n=0;n<r;n++)f.push(H[t++>>0]);else f=f.concat(Ia("(null)".substr(0,r)));
if(b)for(;r<w--;)f.push(32);break;case "c":for(b&&f.push(c("i8"));0<--w;)f.push(32);b||f.push(c("i8"));break;case "n":b=c("i32*");I[b>>2]=f.length;break;case "%":f.push(g);break;default:for(n=m;n<a+2;n++)f.push(G[n>>0])}a+=2}else f.push(g),a+=1}return f}
function qb(a){if(!a||!a.callee||!a.callee.name)return[null,"",""];var b=a.callee.name,c="(",d=!0,f;for(f in a){var g=a[f];d||(c+=", ");d=!1;c="number"===typeof g||"string"===typeof g?c+g:c+("("+typeof g+")")}c+=")";a=(a=a.callee.caller)?a.arguments:[];d&&(c="");return[a,b,c]}
function rb(a){a:{var b=Error();if(!b.stack){try{throw Error();}catch(u){b=u}if(!b.stack){b="(no stack trace available)";break a}}b=b.stack.toString()}b=b.slice(b.indexOf("\n",Math.max(b.lastIndexOf("_emscripten_log"),b.lastIndexOf("_emscripten_get_callstack")))+1);a&32&&da("EM_LOG_DEMANGLE is deprecated; ignoring");a&8&&"undefined"===typeof emscripten_source_map&&(da('Source map information is not available, emscripten_log with EM_LOG_C_STACK will be ignored. Build with "--pre-js $EMSCRIPTEN/src/emscripten-source-map.min.js" linker flag to add source map loading to code.'),
a=a^8|16);var c=null;if(a&128)for(c=qb(arguments);c[1].includes("_emscripten_");)c=qb(c[0]);var d=b.split("\n");b="";var f=/\s*(.*?)@(.*?):([0-9]+):([0-9]+)/,g=/\s*(.*?)@(.*):(.*)(:(.*))?/,h=/\s*at (.*?) \((.*):(.*):(.*)\)/,m;for(m in d){var t=d[m],n;if((n=h.exec(t))&&5==n.length){t=n[1];var r=n[2];var z=n[3];n=n[4]}else if((n=f.exec(t))||(n=g.exec(t)),n&&4<=n.length)t=n[1],r=n[2],z=n[3],n=n[4]|0;else{b+=t+"\n";continue}var w=!1;if(a&8){var v=emscripten_source_map.Ta({line:z,Aa:n});if(w=v&&v.source)a&
64&&(v.source=v.source.substring(v.source.replace(/\\/g,"/").lastIndexOf("/")+1)),b+="    at "+t+" ("+v.source+":"+v.line+":"+v.Aa+")\n"}if(a&16||!w)a&64&&(r=r.substring(r.replace(/\\/g,"/").lastIndexOf("/")+1)),b+=(w?"     = "+t:"    at "+t)+" ("+r+":"+z+":"+n+")\n";a&128&&c[0]&&(c[1]==t&&0<c[2].length&&(b=b.replace(/\s+$/,""),b+=" with values: "+c[1]+c[2]+"\n"),c=qb(c[0]))}return b=b.replace(/\s+$/,"")}
function Xa(a,b,c,d){a||(a=this);this.parent=a;this.X=a.X;this.fa=null;this.id=Sa++;this.name=b;this.mode=c;this.P={};this.R={};this.ga=d}Object.defineProperties(Xa.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});ib();R=Array(4096);cb(P,"/");T("/tmp");T("/home");T("/home/web_user");
(function(){T("/dev");Ga(259,{read:function(){return 0},write:function(b,c,d,f){return f}});eb("/dev/null",259);Fa(1280,Ja);Fa(1536,Ka);eb("/dev/tty",1280);eb("/dev/tty1",1536);var a=Ca();V("random",a);V("urandom",a);T("/dev/shm");T("/dev/shm/tmp")})();
(function(){T("/proc");var a=T("/proc/self");T("/proc/self/fd");cb({X:function(){var b=Ma(a,"fd",16895,73);b.P={ca:function(c,d){var f=Q[+d];if(!f)throw new O(8);c={parent:null,X:{ta:"fake"},P:{da:function(){return f.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();
function Ia(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}b=Array(b+1);var f=b.length;c=0;if(0<f){d=c;f=c+f-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=f)break;b[c++]=h}else{if(2047>=h){if(c+1>=f)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=f)break;b[c++]=224|h>>12}else{if(c+
3>=f)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;a=c-d}else a=0;b.length=a;return b}
var tb={c:function(a,b,c){X=c;try{var d=Z(a);switch(b){case 0:var f=Y();return 0>f?-28:U(d.path,d.flags,0,f).Y;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Y(),d.flags|=f,0;case 12:return f=Y(),ja[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return I[sb()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof W&&g instanceof O||E(g),-g.$}},g:function(a,b,c){X=c;try{var d=Z(a);switch(b){case 21509:case 21505:return d.T?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.T?
0:-59;case 21519:if(!d.T)return-59;var f=Y();return I[f>>2]=0;case 21520:return d.T?-28:-59;case 21531:a=f=Y();if(!d.R.Ba)throw new O(59);return d.R.Ba(d,b,a);case 21523:return d.T?0:-59;case 21524:return d.T?0:-59;default:E("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof W&&g instanceof O||E(g),-g.$}},h:function(a,b,c){X=c;try{var d=a?F(H,a,void 0):"",f=c?Y():0;return U(d,b,f).Y}catch(g){return"undefined"!==typeof W&&g instanceof O||E(g),-g.$}},e:function(a,b,c){b=ob(b,c);b=F(b,0);a&
24&&(b=b.replace(/\s+$/,""),b+=(0<b.length?"\n":"")+rb(a));a&1?a&4?console.error(b):a&2?console.warn(b):a&512?console.info(b):a&256?console.debug(b):console.log(b):a&6?y(b):ca(b)},j:function(a,b,c){H.copyWithin(a,b,b+c)},k:function(a){var b=H.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ea.grow(Math.min(2147483648,d)-ia.byteLength+65535>>>16);la();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},
a:function(a){try{var b=Z(a);if(null===b.Y)throw new O(8);b.ja&&(b.ja=null);try{b.R.close&&b.R.close(b)}catch(c){throw c;}finally{Q[b.Y]=null}b.Y=null;return 0}catch(c){return"undefined"!==typeof W&&c instanceof O||E(c),c.$}},f:function(a,b,c,d){try{a:{for(var f=Z(a),g=a=0;g<c;g++){var h=I[b+(8*g+4)>>2],m=f,t=I[b+8*g>>2],n=h,r=void 0,z=G;if(0>n||0>r)throw new O(28);if(null===m.Y)throw new O(8);if(1===(m.flags&2097155))throw new O(8);if(16384===(m.node.mode&61440))throw new O(31);if(!m.R.read)throw new O(28);
var w="undefined"!==typeof r;if(!w)r=m.position;else if(!m.seekable)throw new O(70);var v=m.R.read(m,z,t,n,r);w||(m.position+=v);var u=v;if(0>u){var q=-1;break a}a+=u;if(u<h)break}q=a}I[d>>2]=q;return 0}catch(D){return"undefined"!==typeof W&&D instanceof O||E(D),D.$}},i:function(a,b,c,d,f){try{var g=Z(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;hb(g,a,d);wa=[g.position>>>0,(M=g.position,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:
~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];I[f>>2]=wa[0];I[f+4>>2]=wa[1];g.ja&&0===a&&0===d&&(g.ja=null);return 0}catch(h){return"undefined"!==typeof W&&h instanceof O||E(h),h.$}},b:function(a,b,c,d){try{a:{for(var f=Z(a),g=a=0;g<c;g++){var h=f,m=I[b+8*g>>2],t=I[b+(8*g+4)>>2],n=void 0,r=G;if(0>t||0>n)throw new O(28);if(null===h.Y)throw new O(8);if(0===(h.flags&2097155))throw new O(8);if(16384===(h.node.mode&61440))throw new O(31);if(!h.R.write)throw new O(28);h.seekable&&h.flags&1024&&hb(h,0,
2);var z="undefined"!==typeof n;if(!z)n=h.position;else if(!h.seekable)throw new O(70);var w=h.R.write(h,r,m,t,n,void 0);z||(h.position+=w);try{if(h.path&&Ta.onWriteToFile)Ta.onWriteToFile(h.path)}catch(q){y("FS.trackingDelegate['onWriteToFile']('"+h.path+"') threw an exception: "+q.message)}var v=w;if(0>v){var u=-1;break a}a+=v}u=a}I[d>>2]=u;return 0}catch(q){return"undefined"!==typeof W&&q instanceof O||E(q),q.$}},d:function(a){var b=Date.now()/1E3|0;a&&(I[a>>2]=b);return b}};
(function(){function a(f){e.asm=f.exports;ea=e.asm.l;la();ma=e.asm.N;oa.unshift(e.asm.m);J--;e.monitorRunDependencies&&e.monitorRunDependencies(J);0==J&&(null!==ra&&(clearInterval(ra),ra=null),K&&(f=K,K=null,f()))}function b(f){a(f.instance)}function c(f){return va().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){y("failed to asynchronously prepare wasm: "+g);E(g)})}var d={a:tb};J++;e.monitorRunDependencies&&e.monitorRunDependencies(J);if(e.instantiateWasm)try{return e.instantiateWasm(d,
a)}catch(f){return y("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return B||"function"!==typeof WebAssembly.instantiateStreaming||sa()||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){y("wasm streaming compile failed: "+g);y("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.m).apply(null,arguments)};e._perseus_get_version=function(){return(e._perseus_get_version=e.asm.n).apply(null,arguments)};e._perseus_decoder_close=function(){return(e._perseus_decoder_close=e.asm.o).apply(null,arguments)};e._perseus_decoder_parse=function(){return(e._perseus_decoder_parse=e.asm.p).apply(null,arguments)};
e._perseus_decoder_get_dither_strength=function(){return(e._perseus_decoder_get_dither_strength=e.asm.q).apply(null,arguments)};e._perseus_decoder_get_dither_type=function(){return(e._perseus_decoder_get_dither_type=e.asm.r).apply(null,arguments)};e._perseus_decoder_clear_temporal=function(){return(e._perseus_decoder_clear_temporal=e.asm.s).apply(null,arguments)};e._perseus_decoder_open_wrapper=function(){return(e._perseus_decoder_open_wrapper=e.asm.t).apply(null,arguments)};
e._perseus_decoder_decode_wrapper=function(){return(e._perseus_decoder_decode_wrapper=e.asm.u).apply(null,arguments)};e._perseus_decoder_decode_base_wrapper=function(){return(e._perseus_decoder_decode_base_wrapper=e.asm.v).apply(null,arguments)};e._perseus_decoder_decode_high_wrapper=function(){return(e._perseus_decoder_decode_high_wrapper=e.asm.w).apply(null,arguments)};e._perseus_decoder_upscale_wrapper=function(){return(e._perseus_decoder_upscale_wrapper=e.asm.x).apply(null,arguments)};
e._perseus_decoder_parse_wrapper=function(){return(e._perseus_decoder_parse_wrapper=e.asm.y).apply(null,arguments)};e._perseus_decoder_get_surface_size=function(){return(e._perseus_decoder_get_surface_size=e.asm.z).apply(null,arguments)};e._perseus_decoder_get_base_hash=function(){return(e._perseus_decoder_get_base_hash=e.asm.A).apply(null,arguments)};e._perseus_start_tracing=function(){return(e._perseus_start_tracing=e.asm.B).apply(null,arguments)};
e._perseus_end_tracing=function(){return(e._perseus_end_tracing=e.asm.C).apply(null,arguments)};e._perseus_decoder_get_last_error_wrapper=function(){return(e._perseus_decoder_get_last_error_wrapper=e.asm.D).apply(null,arguments)};e._perseus_decoder_get_surface=function(){return(e._perseus_decoder_get_surface=e.asm.E).apply(null,arguments)};e._DPIVersion=function(){return(e._DPIVersion=e.asm.F).apply(null,arguments)};e._DPIVersionFull=function(){return(e._DPIVersionFull=e.asm.G).apply(null,arguments)};
e._DPIHash=function(){return(e._DPIHash=e.asm.H).apply(null,arguments)};e._DPIHashShort=function(){return(e._DPIHashShort=e.asm.I).apply(null,arguments)};var sb=e.___errno_location=function(){return(sb=e.___errno_location=e.asm.J).apply(null,arguments)},Pa=e._malloc=function(){return(Pa=e._malloc=e.asm.K).apply(null,arguments)};e._free=function(){return(e._free=e.asm.L).apply(null,arguments)};var pb=e._strlen=function(){return(pb=e._strlen=e.asm.M).apply(null,arguments)},ub;
K=function vb(){ub||wb();ub||(K=vb)};
function wb(){function a(){if(!ub&&(ub=!0,e.calledRun=!0,!fa)){e.noFSInit||jb||(jb=!0,ib(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?V("stdin",e.stdin):fb("/dev/tty","/dev/stdin"),e.stdout?V("stdout",null,e.stdout):fb("/dev/tty","/dev/stdout"),e.stderr?V("stderr",null,e.stderr):fb("/dev/tty1","/dev/stderr"),U("/dev/stdin",0),U("/dev/stdout",1),U("/dev/stderr",1));ya(oa);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=
[e.postRun]);e.postRun.length;){var b=e.postRun.shift();pa.unshift(b)}ya(pa)}}if(!(0<J)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)qa();ya(na);0<J||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=wb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();wb();


  return libDPIModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = libDPIModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return libDPIModule; });
else if (typeof exports === 'object')
  exports["libDPIModule"] = libDPIModule;
